# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hyperFine:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
      - run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
          sudo dpkg -i hyperfine_1.9.0_amd64.deb
          hyperfine --min-runs 5 'sleep 0.2' 'sleep 3.2'
          
      - name: Upload results from hyperFine
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: results.txt
          
  compareTies:
    runs-on: ubuntu-latest
    needs: hyperFine
    steps:
      - name: Download results
        uses: actions/download-artifact@v1
        with:
          name: results
      - name: Display Results
        shell: bash
        run: |
          value=`cat results/results.txt`
          echo The result is $value
          
