# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hyperFine_prev:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
          sudo dpkg -i hyperfine_1.9.0_amd64.deb
          hyperfine --min-runs 5 'sleep 0.2' 'sleep 3.2'
  hyperFine_new:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
          sudo dpkg -i hyperfine_1.9.0_amd64.deb
          hyperfine --min-runs 5 'sleep 0.2' 'sleep 3.2'

  compareTimes:
    runs-on: [ubuntu-latest]
    needs: [hyperFine_prev, hyperFine_new]
    steps:
      - run: |
          echo "Run compare logic here"
