# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  timeChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  hyperFine:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
          sudo dpkg -i hyperfine_1.9.0_amd64.deb
          hyperfine --min-runs 5 'sleep 0.2' 'sleep 3.2'
          
